# Generated by Django 2.0.3 on 2019-03-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('base_path', models.CharField(max_length=2000)),
                ('title', models.CharField(default='', max_length=200)),
                ('subtitle', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('affiliation', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=50)),
                ('hashed_password', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
                ('projects', models.ManyToManyField(related_name='users', to='pipeline_manager.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline_manager.User'),
        ),
    ]
